name: Build
on:
  push:
    branches:
      - *
      - !master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: download SDK
      shell: bash
      run: |
        curl https://github.com/revengenowstudio/win-builds-for-patching/raw/master/win-builds-for-patching.zip -o win-builds-for-cnc-patch.zip

    - name: unpack zip
      uses: action-zip@v1
      with:
        args: unzip -qq win-builds-for-cnc-patch.zip -d win-builds-for-cnc-patch

    - name: install sdk
      run: |
        cd win-builds-for-cnc-patch
        ./win-install.bat

    - name: do build
      run: |
        ./build_dll.bat