name: Build
on:
  push:
    branches: ['*', '!master']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: download SDK
      shell: powershell
      run: |
        curl https://github.com/revengenowstudio/win-builds-for-patching/raw/master/win-builds-for-patching.zip -o win-builds-for-cnc-patch.zip
        Expand-Archive -Path 'win-builds-for-cnc-patch.zip' -DestinationPath 'win-builds-for-cnc-patch'

    - name: install sdk
      run: |
        cd win-builds-for-cnc-patch/win-builds-for-patching
        ls
        cmd /c win-install.bat

    - name: do build
      run: |
        $env:PATH=""
        C:\Windows\System32\cmd.exe /c build_dll.cmd